/**
 * TypeMaster — Avro Phonetic Bangla Lessons (40 lessons)
 *
 * IMPORTANT: Avro is a TRANSLITERATION IME.
 * Students type LATIN KEYS → IME converts to Bangla.
 * Therefore:
 *   - `text` contains what the student PHYSICALLY TYPES (Latin sequences)
 *   - `focusKeys` are the Latin key combos being practiced
 *   - `outputPreview` shows the expected Bangla output (hint only)
 *   - `inputLanguage: "latin"` tells the engine to skip Bangla processing
 *
 * Avro key rules (most common):
 *   Vowels:  o→অ  a→আ  i→ই  I/ee→ঈ  u→উ  U→ঊ  e→এ  O→ও  OI→ঐ  OU→ঔ
 *   Kars:    ka→কা  ki→কি  ku→কু  ke→কে  ko→কো
 *   ক-বর্গ: k→ক  kh→খ  g→গ  gh→ঘ  Ng→ঙ
 *   চ-বর্গ: c→চ  ch→ছ  j→জ  jh→ঝ  NG→ঞ
 *   ট-বর্গ: T→ট  Th→ঠ  D→ড  Dh→ঢ  N→ণ
 *   ত-বর্গ: t→ত  th→থ  d→দ  dh→ধ  n→ন
 *   প-বর্গ: p→প  f/ph→ফ  b→ব  v/bh→ভ  m→ম
 *   Others:  z→য  r→র  l→ল  sh→শ  S→ষ  s→স  h→হ  rr→ড়  RR→ঢ়  y→য়
 *   Conjunct: + or . between letters: bn+dhu→বন্ধু  p+rem→প্রেম
 */
import { Lesson } from "../types";

export const avroLessons: Lesson[] = [

  // ══════════════════════════════════════════════════════════
  // PHASE 1: VOWELS (Lessons 1–5)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-001",
    title: "অ and আ: o and a",
    subtitle: "অ টাইপ করতে 'o' চাপুন, আ টাইপ করতে 'a' চাপুন",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "o a",
    text: "o a o a oo aa oa ao ooa aao oo aa oa ao o a o a ooa aao",
    outputPreview: "অ আ অ আ অঅ আআ অআ আঅ",
    order: 1,
    targetWpm: 8,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-002",
    title: "ই and ঈ: i and I",
    subtitle: "ই টাইপ করতে 'i', ঈ টাইপ করতে 'I' বা 'ee' চাপুন",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "i I ee",
    text: "i I i I ii II iI Ii ee i I ee ii II iI Ii ee",
    outputPreview: "ই ঈ ই ঈ ইই ঈঈ",
    order: 2,
    targetWpm: 8,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-003",
    title: "উ and ঊ: u and U",
    subtitle: "উ টাইপ করতে 'u', ঊ টাইপ করতে 'U' চাপুন",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "u U",
    text: "u U u U uu UU uU Uu uu UU uU Uu u U u U uu UU uU",
    outputPreview: "উ ঊ উ ঊ উউ ঊঊ",
    order: 3,
    targetWpm: 8,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-004",
    title: "এ and ও: e and O",
    subtitle: "এ টাইপ করতে 'e', ও টাইপ করতে 'O' (বড় হাত) চাপুন",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "e O",
    text: "e O e O ee OO eO Oe ee OO eO Oe e O e O",
    outputPreview: "এ ও এ ও এএ ওও",
    order: 4,
    targetWpm: 8,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-005",
    title: "ঐ and ঔ: OI and OU",
    subtitle: "ঐ টাইপ করতে 'OI', ঔ টাইপ করতে 'OU' চাপুন",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "OI OU",
    text: "OI OU OI OU OI OI OU OU OI OU OU OI OI OU OI OU",
    outputPreview: "ঐ ঔ ঐ ঔ ঐঐ ঔঔ",
    order: 5,
    targetWpm: 8,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 2: ক-বর্গ and চ-বর্গ (Lessons 6–9)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-006",
    title: "ক-বর্গ: k kh g gh",
    subtitle: "ক=k, খ=kh, গ=g, ঘ=gh — গলার শব্দ (Velar group)",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "k kh g gh",
    text: "k kh g gh k kh g gh kk kh gg gh kg khg gk ghk kkhg gghk",
    outputPreview: "ক খ গ ঘ ক খ গ ঘ",
    order: 6,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-007",
    title: "ক-বর্গ Words: ka ko ke",
    subtitle: "ক-বর্গের বর্ণ দিয়ে সাধারণ শব্দ: ka=কা, ko=কো, ke=কে",
    category: "bangla",
    level: "beginner",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "k g kh gh a e o",
    text: "ka ki ku ke ko kha khi khu ga gi gu ge go ka ko ka ke",
    outputPreview: "কা কি কু কে কো খা খি খু গা গি গু গে গো",
    order: 7,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-008",
    title: "চ-বর্গ: c ch j jh",
    subtitle: "চ=c, ছ=ch, জ=j, ঝ=jh — তালু শব্দ (Palatal group)",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "c ch j jh",
    text: "c ch j jh c ch j jh cc ch jj jh cj chj jc jhc cchj jjhc",
    outputPreview: "চ ছ জ ঝ চ ছ জ ঝ",
    order: 8,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-009",
    title: "চ-বর্গ Words: cha ji jo",
    subtitle: "চ-বর্গের বর্ণ দিয়ে সাধারণ শব্দ",
    category: "bangla",
    level: "beginner",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "c ch j jh a e i o",
    text: "cha chi chu che cho ja ji ju je jo jha jhi jhu cha jo",
    outputPreview: "চা চি চু চে চো জা জি জু জে জো ঝা ঝি ঝু",
    order: 9,
    targetWpm: 10,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 3: ট-বর্গ, ত-বর্গ, প-বর্গ (Lessons 10–13)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-010",
    title: "ট-বর্গ: T Th D Dh N",
    subtitle: "ট=T, ঠ=Th, ড=D, ঢ=Dh, ণ=N — মূর্ধন্য শব্দ (Retroflex group)",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "T Th D Dh N",
    text: "T Th D Dh N T Th D Dh N TT Th DD Dh NN TD ThD DT DhT",
    outputPreview: "ট ঠ ড ঢ ণ ট ঠ ড ঢ ণ",
    order: 10,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-011",
    title: "ত-বর্গ: t th d dh n",
    subtitle: "ত=t, থ=th, দ=d, ধ=dh, ন=n — দন্ত্য শব্দ (Dental group)",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "t th d dh n",
    text: "t th d dh n t th d dh n tt th dd dh nn td thd dt dht",
    outputPreview: "ত থ দ ধ ন ত থ দ ধ ন",
    order: 11,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-012",
    title: "প-বর্গ: p f b v m",
    subtitle: "প=p, ফ=f/ph, ব=b, ভ=v/bh, ম=m — ওষ্ঠ্য শব্দ (Labial group)",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "p f b v m",
    text: "p f b v m p f b v m pp ff bb vv mm pb fv bm pf vb mp",
    outputPreview: "প ফ ব ভ ম প ফ ব ভ ম",
    order: 12,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-013",
    title: "Mixed Varga Combo: k g c j t d p b m",
    subtitle: "সব বর্গের অনুশীলন একসাথে",
    category: "bangla",
    level: "beginner",
    type: "combo",
    inputLanguage: "latin",
    focusKeys: "k g c j t d p b m",
    text: "ka ga ca ja ta da pa ba ma kg cj td pb km gc jd tb pm",
    outputPreview: "কা গা চা জা তা দা পা বা মা",
    order: 13,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 4: EXTRA CONSONANTS (Lessons 14–16)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-014",
    title: "র ল হ: r l h",
    subtitle: "র=r, ল=l, হ=h — তরল ও অন্তঃস্থ বর্ণ",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "r l h",
    text: "r l h r l h rr ll hh rl hr lh rlh hlr lrh r l h r l h",
    outputPreview: "র ল হ র ল হ রর লল হহ",
    order: 14,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-015",
    title: "শ ষ স য: sh S s z",
    subtitle: "শ=sh, ষ=S, স=s, য=z — সিবিলান্ট ও অন্তঃস্থ",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "sh S s z",
    text: "sh S s z sh S s z sh sh SS ss zz shS Ss Sz shSsz zsSsh",
    outputPreview: "শ ষ স য শ ষ স য",
    order: 15,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-016",
    title: "ড় ঢ় য়: rr RR y",
    subtitle: "ড়=rr, ঢ়=RR, য়=y — বিশেষ Avro বর্ণ",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "rr RR y",
    text: "rr RR y rr RR y rrrr RRRR yy rr RR y rrRR yRR rry RRrr",
    outputPreview: "ড় ঢ় য় ড় ঢ় য়",
    order: 16,
    targetWpm: 10,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 5: VOWEL SIGNS / KARS (Lessons 17–19)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-017",
    title: "আ-কার, ই-কার, ঈ-কার: ka ki kI",
    subtitle: "কার শেখা: ka=কা, ki=কি, kI=কী, ta=তা, ti=তি",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "a i I",
    text: "ka ki kI ta ti tI da di dI ba bi bI ma mi mI ka ki kI",
    outputPreview: "কা কি কী তা তি তী দা দি দী বা বি বী মা মি মী",
    order: 17,
    targetWpm: 12,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-018",
    title: "উ-কার, এ-কার, ও-কার: ku ke ko",
    subtitle: "কার শেখা: ku=কু, ke=কে, ko=কো, tu=তু, te=তে",
    category: "bangla",
    level: "beginner",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "u e O",
    text: "ku ke ko tu te to du de do bu be bo mu me mo ku ke ko",
    outputPreview: "কু কে কো তু তে তো দু দে দো বু বে বো মু মে মো",
    order: 18,
    targetWpm: 12,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-019",
    title: "Kars Practice with Common Syllables",
    subtitle: "মিশ্র কার-যুক্ত অক্ষর: ami, tumi, bari, kore",
    category: "bangla",
    level: "beginner",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "a i u e O",
    text: "ami tumi bari kore deke sone mane boro choto nodi meye",
    outputPreview: "আমি তুমি বাড়ি করে ডেকে সোনে মানে বড়ো ছোটো নদী মেয়ে",
    order: 19,
    targetWpm: 12,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 6: CONJUNCTS with + and . (Lessons 20–22)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-020",
    title: "Conjunct Builder: + notation",
    subtitle: "যুক্তবর্ণ তৈরি: b+n=ব্ন, n+d=ন্দ, s+t=স্ত, k+t=ক্ত",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "+ notation",
    text: "n+d n+t m+p l+p k+t s+t n+t l+m m+m l+k n+d m+p k+t",
    outputPreview: "ন্দ ন্ত ম্প ল্প ক্ত স্ত ন্ত ল্ম ম্ম ল্ক",
    order: 20,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-021",
    title: "Complex Conjuncts: ksh gg jng",
    subtitle: "জটিল যুক্তবর্ণ: ksh=ক্ষ, gg=জ্ঞ, sh+ch=শ্চ",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "ksh gg sh+ch",
    text: "ksh gg sh+ch ksh gg sh+ch c+c t+t ksh gg ksh gg sh+ch",
    outputPreview: "ক্ষ জ্ঞ শ্চ ক্ষ জ্ঞ শ্চ চ্চ ত্ত",
    order: 21,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-avro-022",
    title: "Conjunct Words: bondhu priya",
    subtitle: "যুক্তবর্ণ দিয়ে সাধারণ বাংলা শব্দ",
    category: "bangla",
    level: "intermediate",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "+ conjunct",
    text: "bon+dhu shon+dha shan+ti ksh+oma bij+gyan ek+ti shon+ba",
    outputPreview: "বন্ধু সন্ধ্যা শান্তি ক্ষমা বিজ্ঞান একটি সংবাদ",
    order: 22,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 7: PHOLAS — র্, ্র, ্য, ্ব (Lessons 23–25)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-023",
    title: "রেফ (র্): rr prefix",
    subtitle: "রেফ মানে র + হসন্ত পরবর্তী বর্ণের উপরে: r+k=র্ক, r+m=র্ম",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "rr r+",
    text: "dhor+mo bor+go kor+m kor+ta ar+th dhor+mo bor+go kor+m",
    outputPreview: "ধর্ম বর্গ কর্ম কর্তা অর্থ ধর্ম বর্গ কর্ম",
    order: 23,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-avro-024",
    title: "র-ফলা (্র) and য-ফলা (্য): p+r b+y",
    subtitle: "র-ফলা: p+r=প্র, g+r=গ্র / য-ফলা: b+y=ব্য, sh+y=শ্য",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "+r +y",
    text: "p+rem g+ram sh+reb p+ra k+ri b+yok+ti sh+yam d+yu t+ya",
    outputPreview: "প্রেম গ্রাম শ্রেব প্রা ক্রি ব্যক্তি শ্যাম দ্যু ত্যা",
    order: 24,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-avro-025",
    title: "ব-ফলা (্ব): s+b d+b",
    subtitle: "ব-ফলা: sh+b=শ্ব, s+b=স্ব, d+b=দ্ব",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    inputLanguage: "latin",
    focusKeys: "+b",
    text: "sh+bop+no s+ba+dhin d+bi b+ya b+yok+ti sh+bop+no s+ba",
    outputPreview: "স্বপ্ন স্বাধীন দ্বি ব্যা ব্যক্তি স্বপ্ন স্বা",
    order: 25,
    targetWpm: 10,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 8: COMMON WORDS (Lessons 26–28)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-026",
    title: "Top Common Words 1: ami tumi se",
    subtitle: "সবচেয়ে বেশি ব্যবহৃত বাংলা শব্দ দিয়ে অনুশীলন",
    category: "bangla",
    level: "intermediate",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "common words",
    text: "ami tumi se ama+der toma+der ta+der ei she+i ki+n+tu ar",
    outputPreview: "আমি তুমি সে আমাদের তোমাদের তাদের এই সেই কিন্তু আর",
    order: 26,
    targetWpm: 14,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-027",
    title: "Top Common Words 2: kora hOoa bola",
    subtitle: "সর্বাধিক ব্যবহৃত ক্রিয়াপদ দিয়ে অনুশীলন",
    category: "bangla",
    level: "intermediate",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "common verbs",
    text: "ko+ra hO+wa bo+la de+kha she+na ja+wa a+sha tha+ka chan+a",
    outputPreview: "করা হওয়া বলা দেখা শোনা যাওয়া আসা থাকা চাওয়া",
    order: 27,
    targetWpm: 14,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-028",
    title: "Top Common Words 3: Mixed Nouns",
    subtitle: "সাধারণ বাংলা বিশেষ্য শব্দ দিয়ে অনুশীলন",
    category: "bangla",
    level: "intermediate",
    type: "word",
    inputLanguage: "latin",
    focusKeys: "common nouns",
    text: "bash sha man+ush desh nodi akash ba+ta+sh ma ba+ba bha+i bo+n",
    outputPreview: "বাস শহর মানুষ দেশ নদী আকাশ বাতাস মা বাবা ভাই বোন",
    order: 28,
    targetWpm: 14,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 9: SENTENCES (Lessons 29–34)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-029",
    title: "Simple Sentences 1",
    subtitle: "ছোট সহজ বাক্য — Avro ফোনেটিকে প্রথম বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "ami bangla+y ko+tha bo+li. bangla a+mar ma+tri+bha+sha. a+mi bang+la bha+sha+ke a+ne+k bha+lo+ba+si e+bo+ng ta+r gorob bo+ho+n ko+ri.",
    outputPreview: "আমি বাংলায় কথা বলি। বাংলা আমার মাতৃভাষা।",
    order: 29,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-030",
    title: "Simple Sentences 2",
    subtitle: "দৈনন্দিন জীবনের ছোট বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "a+nek dha+nyo+bad. a+p+ni ke+mon a+chen? ami bha+lo a+chi. a+p+nar sha+rirk a+bhas+tha ba+lo a+che to?",
    outputPreview: "অনেক ধন্যবাদ। আপনি কেমন আছেন? আমি ভালো আছি।",
    order: 30,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-031",
    title: "Daily Conversation",
    subtitle: "প্রাত্যহিক কথোপকথনের বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "a+j a+bha+wa ba+lo ache. ni+l a+kash e shak+la me+gh bhe+she be+rach+che. e+mon din e mon a+ne+k pro+shon+no thak+e.",
    outputPreview: "আজ আবহাওয়া ভালো আছে। নীল আকাশে সাদা মেঘ ভেসে বেড়াচ্ছে।",
    order: 31,
    targetWpm: 16,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-032",
    title: "Mixed Sentences: All Varga",
    subtitle: "সব বর্গের বর্ণ ব্যবহার করে সম্পূর্ণ বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "sha+hin sha+re+r ga+n ga+i+lo. bo+no+ta+la+r fa+l kha+bo. e+ka+ne a+nek fo+ler ga+ch ro+ye+che ja mon ke sat+e+j ko+re.",
    outputPreview: "শাহিন সুরের গান গাইলো। বনতলার ফল খাবো।",
    order: 32,
    targetWpm: 16,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-033",
    title: "Sentences with Conjuncts",
    subtitle: "যুক্তবর্ণ সহ বাক্য টাইপিং অনুশীলন",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    inputLanguage: "latin",
    focusKeys: "conjunct sentences",
    text: "bij+gyan a+ma+der ji+bon pa+ri+bo+rton ko+re+che. shik+kha j+ga+ner a+lo. j+gyan sha+ba+r jon+nyo muk+to thak+a u+ci+t.",
    outputPreview: "বিজ্ঞান আমাদের জীবন পরিবর্তন করেছে। শিক্ষা জ্ঞানের আলো।",
    order: 33,
    targetWpm: 16,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-034",
    title: "Sentences with All Pholas",
    subtitle: "সব ধরনের ফোলা সহ বাক্য",
    category: "bangla",
    level: "advanced",
    type: "sentence",
    inputLanguage: "latin",
    focusKeys: "phola sentences",
    text: "dhor+mo e+bong kor+m dui+tai g+urutt+wopurno. p+riti a+r sh+radhdha j+ga+r o+shikhD. sha+ba+r sho+he+jogit+a a+ma+der ka+je go+ti a+ne.",
    outputPreview: "ধর্ম এবং কর্ম দুইটাই গুরুত্বপূর্ণ। প্রীতি আর শ্রদ্ধা জগরে অশিকড়।",
    order: 34,
    targetWpm: 18,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 10: PARAGRAPHS + MASTERY (Lessons 35–40)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-avro-035",
    title: "Paragraph 1: আমাদের বাংলাদেশ",
    subtitle: "বাংলাদেশের পরিচয় নিয়ে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "a+ma+der desh bang+la+desh. e+desh nodi+mat+rik o shu+jola shu+fola. e+desher man+ush ot+yan+to sho+rol o oti+thi po+ra+yon. nodir pa+re shobuj ga+cher sa+ri a+r pakh+ir kacho+mico shobdho shon+a ja+y. e+khan+kar ma+ti o jola+ba+yu krishi ka+jer jon+nyo o+ti upo+jo+gi.",
    outputPreview: "আমাদের দেশ বাংলাদেশ। এদেশ নদীমাতৃক ও সুজলা সুফলা। এদেশের মানুষ অত্যন্ত সরল ও অতিথিপরায়ণ।",
    order: 35,
    targetWpm: 18,
    targetAccuracy: 90,
  },
  {
    id: "bn-avro-036",
    title: "Paragraph 2: কম্পিউটার ও প্রযুক্তি",
    subtitle: "আধুনিক প্রযুক্তি নিয়ে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "kom+piu+tar pra+juk+ti a+ma+der ji+bo+n ke shoho+j ko+re+che. internet er mo+dhyo+me tottho a+dan pro+dan kora e+khon o+nek shoho+j hoy+eche. e+khon ghore bo+she+i p+rithibir shob khobor pa+o+ya ja+y. tottho pra+juk+ti amader kormo+khetro ke a+nek dho+p e e+gi+ye niye ge+che.",
    outputPreview: "কম্পিউটার প্রযুক্তি আমাদের জীবনকে সহজ করেছে। ইন্টারনেটের মাধ্যমে তথ্য আদান প্রদান করা এখন অনেক সহজ হয়েছে।",
    order: 36,
    targetWpm: 20,
    targetAccuracy: 92,
  },
  {
    id: "bn-avro-037",
    title: "Paragraph 3: ভাষা আন্দোলন",
    subtitle: "১৯৫২ সালের ভাষা আন্দোলন নিয়ে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "1952 sha+ler bha+sha an+do+lon a+ma+der i+ti+hash er e+k sho+na+li odhdha+y. sha+hid+ra ta+der rok+to die bang+la bha+sha+ke rong+sha ko+re+chen. ta+der rok+ter bi+ni+mo+ye pa+o+ya mat+ri+bha+sha a+ma+der a+o+lon+kar. amra protidin e+i bha+shar mor+jada rok+kha kor+ar p+ro+tig+gya ko+ri.",
    outputPreview: "১৯৫২ সালের ভাষা আন্দোলন আমাদের ইতিহাসের এক সোনালি অধ্যায়। শহীদরা তাদের রক্ত দিয়ে বাংলা ভাষাকে রক্ষা করেছেন।",
    order: 37,
    targetWpm: 20,
    targetAccuracy: 92,
  },
  {
    id: "bn-avro-038",
    title: "Speed Builder 1",
    subtitle: "গতি বৃদ্ধিকরণ অনুশীলন — দ্রুত ও নির্ভুলভাবে",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "go+ti+shil o nir+bhul ta+r jonnyo tai+ping on+ush+ilan er ko+no bi+kol+po nei. p+ro+ti+din on+tot pon+dhoro mi+nit ni+yom me+ne tai+p ko+rar ob+hyas rakha jo+ruri. nira+bos+chin+no cor+cha a+ma+der a+n+gul er sh+porsho ke shto shto gune do+ksho ko+re to+le.",
    outputPreview: "গতিশীলতা ও নির্ভুলতা অর্জনের জন্য টাইপিং অনুশীলনের কোনো বিকল্প নেই। প্রতিদিন অন্তত পনেরো মিনিট নিয়ম মেনে টাইপ করার অভ্যাস রাখা জরুরি।",
    order: 38,
    targetWpm: 22,
    targetAccuracy: 93,
  },
  {
    id: "bn-avro-039",
    title: "Speed Builder 2",
    subtitle: "উচ্চতর গতির চ্যালেঞ্জ",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "bang+la bha+sha a+ma+der p+ra+ner bha+sha. a+ma+ra ta+der at+mot+yag ci+ro+din sh+rod+dhabhore sh+mo+ron kor+bo. ma+tri+bha+sha+r p+ro+ti bha+lo+ba+sha o e+r shoi+hik cor+cha a+ma+der gor+ber p+ro+tik. a+p+nar tai+ping go+ti a+p+nar dainik ka+jer shoi+l+yo ke a+nek sundor ko+ri.",
    outputPreview: "বাংলা ভাষা আমাদের প্রাণের ভাষা। আমরা তাদের আত্মত্যাগ চিরদিন শ্রদ্ধাভরে স্মরণ করব। মাতৃভাষার প্রতি ভালোবাসা ও এর সঠিক চর্চা আমাদের গর্বের প্রতীক।",
    order: 39,
    targetWpm: 24,
    targetAccuracy: 94,
  },
  {
    id: "bn-avro-040",
    title: "Final Avro Mastery Challenge",
    subtitle: "অভ্র ফোনেটিকের চূড়ান্ত পরীক্ষা — সর্বোচ্চ গতি ও নির্ভুলতা",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    inputLanguage: "latin",
    focusKeys: "all",
    text: "di+ji+tal mad+hyo+me bang+la le+khar jon+nyo shoih+hik le+a+ut jan+a ot+tan+to do+rka+ri. ki+bord sh+por+sha ko+re ok+shor ce+nar ob+hyas a+ma+der tai+ping dok+sha ko+re to+le. nir+bhul tai+ping shta shomoy e ka+j shesh kor+te sha+ha+j+yo ko+re.",
    outputPreview: "ডিজিটাল মাধ্যমে বাংলা লেখার জন্য সঠিক লেআউট জানা অত্যন্ত দরকারি। কীবোর্ড স্পর্শ করে অক্ষর চেনার অভ্যাস আমাদের টাইপিং দক্ষ করে তোলে।",
    order: 40,
    targetWpm: 25,
    targetAccuracy: 95,
  },
];
