/**
 * TypeMaster — Inscript Bangla Lessons (45 lessons)
 *
 * Jatiya layout FIXED LAYOUT.
 * Each physical key maps to a specific Bangla character.
 *
 * Key Zones (physical QWERTY positions):
 *   HOME ROW:  a=অ  s=স  d=্  f=া  g=ক  h=ব  j=ন  k=ত  l=ম  ;=র
 *   TOP ROW:   q=ৌ  w=ূ  e=ী  r=ু  t=ি  y=ত  u=চ  i=দ  o=জ  p=ড
 *   BOTTOM ROW: z=্র  x=ও  c=ে  v=প  b=ল  n=ষ  m=হ  /=য়
 *   SHIFT HOME: A=আ  S=শ  D=।  F=ঋ  G=ঙ  H=ভ  J=ণ  K=থ  L=ধ  ;=ড়
 *   SHIFT TOP:  Q=ঔ  W=ঊ  E=ঈ  R=উ  T=ই  Y=থ  U=ছ  I=ধ  O=ঝ  P=ঢ
 */
import { Lesson } from "../types";

export const inscriptLessons: Lesson[] = [

  // ══════════════════════════════════════════════════════════
  // PHASE 1: HOME ROW — LEFT HAND (Lessons 1–5)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-001",
    title: "Home Row Left: ক স (k m)",
    subtitle: "k=ক এবং m=স — বাম হাতের তর্জনী ও অনামিকা আঙুল",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ক স",
    text: "ক স ক স কক সস কস সক কক সস কক সস কস সক সক কস ককস সকক",
    order: 1,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-002",
    title: "Home Row Left: া ্ (e d)",
    subtitle: "e=া (আ-কার) এবং d=্ (হসন্ত/লিঙ্ক কী) — তর্জনী ও মধ্যমা",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "া ্",
    text: "া ্ া ্ াা ্্ া্ ্া াা ্্ াা ্্ া্ ্া ্া া্ াা্ ্াা",
    order: 2,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-003",
    title: "Home Row Right: ব ন (y v)",
    subtitle: "y=ব এবং v=ন — ডান হাতের তর্জনী দুটো",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ব ন",
    text: "ব ন ব ন বব নন বন নব বব নন বব নন বন নব নব বন ববন নবব",
    order: 3,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-004",
    title: "Home Row Right: ত ম র (l c j)",
    subtitle: "l=ত, c=ম, j=র — ডান হাতের মধ্যমা, অনামিকা ও কনিষ্ঠা",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ত ম র",
    text: "ত ম র তমর রমত তত মম রর তমর রমত তমর রমত তত মম রর তমর",
    order: 4,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-005",
    title: "Home Row: অ (d) — Independent Vowel",
    subtitle: "Shift+Shift+d=অ — স্বাধীন স্বরবর্ণ অ",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "অ",
    text: "অ অ অঅ অঅঅ অ অ অঅ অঅঅ অক অস অত অন অম অর অক অস অত",
    order: 5,
    targetWpm: 8,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 2: HOME ROW COMBOS (Lessons 6–7)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-006",
    title: "Home Row Left Combo: অ স া ্ ক",
    subtitle: "বাম হাতের হোম রো কী (a, s, d, f, g) একসাথে",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "অ স া ্ ক",
    text: "কা সা আস ক্ ত্ কা সা আস ক্ ত্ কাসা আক্ সাক্ কাসা আক্",
    order: 6,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-007",
    title: "Home Row Full Mix: Kars + Consonants",
    subtitle: "সম্পূর্ণ হোম সারির সমন্বিত অভ্যাস",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "অ স া ক ব ন ত ম র",
    text: "কা সা বা না তা মা রা কস বন তমর কা সা বা না তা মা রা",
    order: 7,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 3: TOP ROW (Lessons 8–14)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-008",
    title: "Top Row Left Vowels: ৌ ূ ী ু ি (q t r g f)",
    subtitle: "Shift+q=ৌ, Shift+t=ূ, Shift+r=ী, g=ু, f=ি — বাম হাতের উপরের সারির স্বর-কার",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ৌ ূ ী ু ি",
    text: "ৌ ূ ী ু ি ৌূ ীু িৌ ূী ুি ৌৌ ূূ ীী ুু িি ৌূ ীু িৌূীুি",
    order: 8,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-009",
    title: "Top Row Right Consonants: ত চ দ জ ড (l ; o p [)",
    subtitle: "l=ত, ;=চ, o=দ, p=জ, [=ড — ডান হাতের উপরের সারি",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ত চ দ জ ড",
    text: "ত চ দ জ ড তচ দজ ডত চদ জড তত চচ দদ জজ ডড তচ দজ ডতচদজড",
    order: 9,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-010",
    title: "Top Row Left Vowels + Right Consonants Combo",
    subtitle: "কার চিহ্ন ও ব্যঞ্জনবর্ণ মিলিয়ে অক্ষর তৈরি",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "ি ু ী ত চ দ জ ড",
    text: "তি তু তী চি চু দি দু জি জু ডি ডু তিতু চিচু দিদু জিজু",
    order: 10,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-011",
    title: "Top Row Left Combo: ৌ ূ ী ু ি",
    subtitle: "বাম হাতের টপ কীবোর্ড রো কীগুলোর ড্রিল",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "ৌ ূ ী ু ি",
    text: "ৌ ূ ী ু ি ৌূ ীু ুী িৌ ৌূীুি িুীূৌ কৌ কূ কী কু কি",
    order: 11,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-012",
    title: "Top Row Right Combo: ত চ দ জ ড",
    subtitle: "ডান হাতের টপ কীবোর্ড রো কীগুলোর ড্রিল",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "ত চ দ জ ড",
    text: "ত চ দ জ ড তচ দজ ডত চদ জড তচদজড ডজদচত তচদজড ডজদচত",
    order: 12,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-013",
    title: "Top Row Full Mix",
    subtitle: "উপরের সারির সমন্বিত টাইপিং অনুশীলন",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "ৌ ূ ী ু ি ত চ দ জ ড",
    text: "ৌূ ীু িৌূীু তচ দজ ডতচদজ ৌূীুি তচদজড তি চু দী জু ডি",
    order: 13,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 4: BOTTOM ROW (Lessons 14–16)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-014",
    title: "Bottom Row Left: ্র ও ে (a s)",
    subtitle: "d=্র, Shift+a=ও, s=ে — বাম হাতের নীচের তিনটি কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "্র ও ে",
    text: "্র ও ে ্রও ে্র ্র্র ওও েে ্রও ে্র ্রও ে্র ্র্র ওও েে",
    order: 14,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-015",
    title: "Bottom Row Right: প ল ষ হ য় (h n , u)",
    subtitle: "h=প, Shift+n=ল, Shift+Shift+,=ষ, u=হ, /=য় — ডান হাতের নীচের কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "প ল ষ হ য়",
    text: "প ল ষ হ য় পল ষহ য়প লষ হয় পপ লল ষষ হহ য়য় পলষহয় য়হষলপ",
    order: 15,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-016",
    title: "Bottom Row Full Mix",
    subtitle: "নীচের সারির সব অক্ষরের সমন্বিত কীবোর্ড টাইপ",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "্র ও ে প ল ষ হ য়",
    text: "্র ও ে প ল ষ হ য় ্রও েপ লষ হয় পপ লল ষষ হহ য়য়",
    order: 16,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 5: ALL ROWS SIMPLE WORDS (Lesson 17)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-017",
    title: "All Rows Combined Simple Words",
    subtitle: "শিফট কী ছাড়া সাধারণ বাংলা শব্দের ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "করন গরম চটি পকেট জেলি রতি গবম পতন চমক রগড় হিমজ তকরি",
    order: 17,
    targetWpm: 15,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 6: SHIFT KEYS — HOME ROW (Lessons 18–20)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-018",
    title: "Shift Home Left: আ শ । (e m .)",
    subtitle: "Shift+e=আ, Shift+Shift+m=শ, Shift+Shift+.=। — শিফট+বাম হোম রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "আ শ ।",
    text: "আ শ । আ শ । আশ ।আ শ। আআ শশ ।। আশ ।আ শ। আআ শশ ।। আশ।",
    order: 18,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-inscript-019",
    title: "Shift Home Right: ভ ণ থ ধ ড় (y c l o)",
    subtitle: "Shift+Shift+y=ভ, Shift+Shift+c=ণ, Shift+Shift+l=থ, Shift+Shift+o=ধ, [=ড় — শিফট+ডান হোম রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "ভ ণ থ ধ ড়",
    text: "ভ ণ থ ধ ড় ভণ থধ ড়ভ ণথ ভভ ণণ থথ ধধ ড়ড় ভণথধ ধথণভ",
    order: 19,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-inscript-020",
    title: "Shift Home Full Combo: আ শ ভ ণ থ ধ ড়",
    subtitle: "হোম সারির শিফট বর্ণের সমন্বিত ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "combo",
    focusKeys: "আ শ ভ ণ থ ধ ড়",
    text: "আ শ ভ ণ থ ধ ড় আশ ভণ থধ ড়আ শভ ণথ ধড় আশভণ থধড়আ",
    order: 20,
    targetWpm: 12,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 7: SHIFT KEYS — TOP ROW (Lessons 21–22)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-021",
    title: "Shift Top Left: ঔ ঊ ঈ উ ই (q t r g f)",
    subtitle: "Shift+q=ঔ, Shift+t=ঊ, Shift+r=ঈ, Shift+g=উ, Shift+f=ই — শিফট+বাম টপ রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "ঔ ঊ ঈ উ ই",
    text: "ঔ ঊ ঈ উ ই ঔঊ ঈউ ইঔ ঊঈ উই ঔঔ ঊঊ ঈঈ উউ ইই ঔঊঈউই ইউঈঊঔ",
    order: 21,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-inscript-022",
    title: "Shift Top Right: থ ছ ধ ঝ ঢ (l ; o p [)",
    subtitle: "Shift+Shift+l=থ, Shift+Shift+;=ছ, Shift+Shift+o=ধ, Shift+Shift+p=ঝ, Shift+Shift+[=ঢ — শিফট+ডান টপ রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "থ ছ ধ ঝ ঢ",
    text: "থ ছ ধ ঝ ঢ থছ ধঝ ঢথ ছধ জঢ থথ ছছ ধধ ঝঝ ঢঢ থছধ ঝঢথ ছধঝ",
    order: 22,
    targetWpm: 10,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 8: SHIFT KEYS — BOTTOM ROW (Lesson 23)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-023",
    title: "Shift Bottom Row: ্য ঐ ৈ ফ ঢ় শ ঞ ৎ ং ঃ",
    subtitle: "নীচের রো-র শিফট কীগুলোর অনুশীলন",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্য ঐ ৈ ফ ঢ় শ ঞ ৎ ং ঃ",
    text: "্য ঐ ৈ ফ ঢ় শ ঞ ৎ ং ঃ ্যঐ ৈফ ঢ়শ ঞৎ ংঃ ্য্য ঐঐ ৈৈ ফফ",
    order: 23,
    targetWpm: 10,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 9: NUMBERS (Lessons 24–26)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-024",
    title: "Numbers: ১ ২ ৩ ৪ ৫",
    subtitle: "জাতীয় কীবোর্ডে সংখ্যা ১ থেকে ৫",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "১ ২ ৩ ৪ ৫",
    text: "১২৩৪৫ ৫৪৩২১ ১১ ২২ ৩৩ ৪৪ ৫৫ ১২ ২৩ ৩৪ ৪৫ ৫১ ১২৩ ২৩৪ ৩৪৫",
    order: 24,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-025",
    title: "Numbers: ৬ ৭ ৮ ৯ ০",
    subtitle: "জাতীয় কীবোর্ডে সংখ্যা ৬ থেকে ০",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "৬ ৭ ৮ ৯ ০",
    text: "৬৭৮৯০ ০৯৮৭৬ ৬৬ ৭৭ ৮৮ ৯৯ ০০ ৬৭ ৭৮ ৮৯ ৯০ ০৬ ৬৭৮ ৭৮৯ ৮৯০",
    order: 25,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-026",
    title: "Numbers Full Combo: ১–০",
    subtitle: "জাতীয় লেআউটে সব বাংলা সংখ্যা একসাথে",
    category: "bangla",
    level: "intermediate",
    type: "combo",
    focusKeys: "১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯ ০",
    text: "১২৩৪৫৬৭৮৯০ ০৯৮৭৬৫৪৩২১ ১২৩৪ ৫৬৭৮ ৯০১২ ৩৪৫৬ ৭৮৯০",
    order: 26,
    targetWpm: 14,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 10: CONJUNCTS (Lessons 27–28)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-027",
    title: "Simple Conjuncts: ক্ত ন্দ ন্ত ম্প (d k l v o c h n m)",
    subtitle: "সহজ যুক্তবর্ণ — d = ্ (হসন্ত/লিঙ্ক কী)",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্ ক ত ন দ ম প ল স",
    text: "ক্ত ন্দ ন্ত ম্প ল্প ম্ম ল্ম ল্ক স্ত ন্দ ন্ত ম্প ল্প ম্ম ল্ম",
    order: 27,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-028",
    title: "Complex Conjuncts: ক্ষ জ্ঞ শ্চ",
    subtitle: "জটিল যুক্তবর্ণ — ক্ষ, জ্ঞ, শ্চ, চ্চ, ত্ত",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্ ক ষ জ ঞ শ চ ত",
    text: "ক্ষ জ্ঞ শ্চ চ্চ ত্ত ক্ষ জ্ঞ শ্চ চ্চ ত্ত ক্ষমা জ্ঞান নিশ্চয়",
    order: 28,
    targetWpm: 10,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 11: VARGA ASPIRATED PAIRS (Lessons 29–33)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-029",
    title: "ক-বর্গ Pairs: ক↔খ গ↔ঘ",
    subtitle: "ক (g) ↔ খ (Shift+g) পেয়ার ড্রিল — একসাথে অনুশীলন",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "ক খ গ ঘ",
    text: "ক খ ক খ কখ খক কক খখ গ ঘ গ ঘ গঘ ঘগ গগ ঘঘ কখগঘ ঘঘখক",
    order: 29,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-030",
    title: "চ-বর্গ Pairs: চ↔ছ জ↔ঝ",
    subtitle: "চ (u) ↔ ছ (Shift+u) এবং জ (o) ↔ ঝ (Shift+o) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "চ ছ জ ঝ",
    text: "চ ছ চ ছ চছ ছচ চচ ছছ জ ঝ জ ঝ জঝ ঝজ জজ ঝঝ চছজঝ ঝঝছচ",
    order: 30,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-031",
    title: "ট-বর্গ Pairs: ট↔ঠ ড↔ঢ",
    subtitle: "জাতীয় কীবোর্ডে ট ↔ ঠ এবং ড ↔ ঢ পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "ট ঠ ড ঢ",
    text: "ট ঠ ট ঠ টঠ ঠট টট ঠঠ ড ঢ ড ঢ ডঢ ঢড ডড ঢঢ টঠডঢ ঢঢঠট",
    order: 31,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-032",
    title: "ত-বর্গ Pairs: ত↔থ দ↔ধ",
    subtitle: "ত (k) ↔ থ (Shift+y) এবং দ (i) ↔ ধ (Shift+i) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "ত থ দ ধ",
    text: "ত থ ত থ তথ থত তত থথ দ ধ দ ধ দধ ধদ দদ ধধ তথদধ ধধথত",
    order: 32,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-033",
    title: "প-বর্গ Pairs: প↔ফ ব↔ভ",
    subtitle: "প (v) ↔ ফ (Shift+v) এবং ব (h) ↔ ভ (Shift+h) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "প ফ ব ভ",
    text: "প ফ প ফ পফ ফপ পপ ফফ ব ভ ব ভ বভ ভব বব ভভ পফবভ ভভফপ",
    order: 33,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 12: PHOLA LESSONS (Lessons 34–37)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-034",
    title: "রেফ (র্): ধর্ম বর্গ কর্ম",
    subtitle: "রেফ = র + হসন্ত পরবর্তী বর্ণের উপরে লেখা হয়",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "র্",
    text: "র্ক র্ম র্ত র্প ধর্ম বর্গ কর্ম অর্থ পর্দা সর্ব ধর্ম বর্গ",
    order: 34,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-035",
    title: "র-ফলা (্র): প্রেম গ্রাম",
    subtitle: "র-ফলা = ব্যঞ্জনবর্ণ + হসন্ত + র → বর্ণের নিচে ছোট র",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্র",
    text: "ক্র গ্র প্র ত্র ব্র ম্র প্রেম গ্রাম দ্রুত ত্রাণ ব্রত ক্রম",
    order: 35,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-036",
    title: "য-ফলা (্য): বিদ্যা আত্যন্ত",
    subtitle: "য-ফলা = ব্যঞ্জনবর্ণ + হসন্ত + য → বর্ণের নিচে ছোট য",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্য",
    text: "ক্য গ্য ত্য ব্য ন্য বিদ্যা আত্যন্ত সত্য ন্যায় ভদ্য রাজ্য",
    order: 36,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-inscript-037",
    title: "ব-ফলা (্ব): স্বপ্ন দ্বিতীয়",
    subtitle: "ব-ফলা = ব্যঞ্জনবর্ণ + হসন্ত + ব → বর্ণের নিচে ছোট ব",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্ব",
    text: "ক্ব ত্ব দ্ব শ্ব স্ব স্বপ্ন স্বাধীন দ্বিতীয় দ্বার ব্যক্তি শ্বাস",
    order: 37,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 13: COMMON WORD FREQUENCY DRILLS (Lessons 38–39)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-038",
    title: "Top 25 Common Words Part 1",
    subtitle: "সর্বাধিক ব্যবহৃত ২৫টি বাংলা শব্দের প্রথম দল",
    category: "bangla",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "আমি তুমি সে আমরা তোমরা এই সেই এবং কিন্তু তার তাদের আমার তোমার",
    order: 38,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "bn-inscript-039",
    title: "Top 25 Common Words Part 2",
    subtitle: "সর্বাধিক ব্যবহৃত ২৫টি বাংলা শব্দের দ্বিতীয় দল",
    category: "bangla",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "করা হওয়া বলা দেখা যাওয়া আসা থাকা দেওয়া নেওয়া জানা শোনা পাওয়া",
    order: 39,
    targetWpm: 15,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 14: SENTENCES + PARAGRAPHS (Lessons 40–45)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-inscript-040",
    title: "Sentences 1: Daily Life",
    subtitle: "দৈনন্দিন জীবনের সহজ বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    focusKeys: "all",
    text: "প্রমিত বাংলা কীবোর্ড ব্যবহারে গতি ও নির্ভুলতা দুটোই বাড়ে। আমাদের জাতীয় কীবোর্ড লেআউটটি বৈজ্ঞানিক উপায়ে তৈরি করা হয়েছে।",
    order: 40,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "bn-inscript-041",
    title: "Sentences 2: About Typing",
    subtitle: "টাইপিং সম্পর্কিত বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    focusKeys: "all",
    text: "জাতীয় কীবোর্ড হল সরকারের অনুমোদিত একমাত্র প্রমিত কীবোর্ড লেআউট। সকল সরকারি ও প্রাতিষ্ঠানিক কাজে এই লেআউটটি ব্যবহার করা বাধ্যতামূলক।",
    order: 41,
    targetWpm: 16,
    targetAccuracy: 90,
  },
  {
    id: "bn-inscript-042",
    title: "Paragraph 1: Jatiya Layout",
    subtitle: "জাতীয় কীবোর্ড সম্পর্কে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    focusKeys: "all",
    text: "জাতীয় কীবোর্ড লেআউট আয়ত্ত করা প্রাথমিক অবস্থায় কিছুটা কঠিন মনে হতে পারে। তবে নিয়মিত ও সঠিক নিয়মে অনুশীলন করলে খুব দ্রুত নির্ভুল ও গতিশীল টাইপিং করা সম্ভব। আঙুলগুলোকে সর্বদা হোম রো-তে ফিরিয়ে আনার অভ্যাসই গতি বাড়ানোর প্রধান চাবিকাঠি।",
    order: 42,
    targetWpm: 18,
    targetAccuracy: 92,
  },
  {
    id: "bn-inscript-043",
    title: "Paragraph 2: Language & Professionalism",
    subtitle: "ভাষা ও পেশাদারিত্ব নিয়ে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    focusKeys: "all",
    text: "প্রমিত পদ্ধতিতে বাংলা লেখা আমাদের সকলের নাগরিক দায়িত্ব। টাইপমাস্টার বাংলা আপনার পেশাদার কীবোর্ড টাইপিং দক্ষতা অর্জনে সর্বদা বিশ্বস্ত সহায়ক হিসেবে কাজ করে যাবে। সঠিক টাইপিং কায়দা আপনাকে ডিজিটাল দুনিয়ায় আরও আত্মবিশ্বাসী করে তুলবে।",
    order: 43,
    targetWpm: 20,
    targetAccuracy: 92,
  },
  {
    id: "bn-inscript-044",
    title: "Speed Builder",
    subtitle: "উচ্চ গতিতে টাইপিং অনুশীলন — জাতীয় লেআউট",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "গতিশীলতা ও নির্ভুলতা অর্জনের জন্য কীবোর্ড টাইপিং অনুশীলনের কোনো বিকল্প নেই। প্রতিদিন অন্তত পনেরো থেকে ত্রিশ মিনিট নিয়ম মেনে টাইপ করার অভ্যাস রাখা জরুরি। সঠিক পোস্টার বজায় রাখলে দীর্ঘ সময় টাইপ করলেও হাতের ক্লান্তি আসে না।",
    order: 44,
    targetWpm: 22,
    targetAccuracy: 93,
  },
  {
    id: "bn-inscript-045",
    title: "Final Jatiya Mastery Challenge",
    subtitle: "জাতীয় কীবোর্ডের চূড়ান্ত পরীক্ষা",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "বাংলা ভাষার প্রমিত রূপ ডিজিটাল মাধ্যমে বজায় রাখতে প্রমিত জাতীয় কীবোর্ড লেআউটের ভূমিকা অপরিসীম। টাইপমাস্টার বাংলা আপনার টাইপিং গতি ও কাজের দক্ষতা বৃদ্ধিতে সর্বোচ্চ সহায়তা দেবে। সঠিক কীবোর্ড শিক্ষার মাধ্যমে নিজের কর্মদক্ষতা বাড়িয়ে নিন।",
    order: 45,
    targetWpm: 25,
    targetAccuracy: 95,
  },
];
