/**
 * TypeMaster — UniBijoy Bangla Lessons (45 lessons)
 *
 * UniBijoy is a FIXED LAYOUT — each physical key maps to a specific Bangla character.
 * Students must memorize key positions and build muscle memory.
 *
 * Key Zones (physical QWERTY positions):
 *   HOME ROW:  a=ৃ  s=ু  d=ি  f=া  g=্  h=ব  j=ক  k=ত  l=দ  ;=স
 *   TOP ROW:   q=ঙ  w=য  e=ড  r=প  t=ট  y=চ  u=জ  i=হ  o=গ  p=ড়  [=ৃ  ]=ে
 *   BOTTOM ROW: z=্র  x=ও  c=ে  v=র  b=ব  n=ন  m=ষ
 *   SHIFT HOME: A=ঋ  S=ূ  D=ী  F=আ  G=অ  H=ভ  J=খ  K=থ  L=ধ  :=ষ
 *   SHIFT TOP:  Q=ঙ  W=্য  E=ঢ  R=ফ  T=ঠ  Y=ছ  U=ঝ  I=ঞ  O=ঘ  P=ঢ়
 */
import { Lesson } from "../types";

export const unibijoyLessons: Lesson[] = [

  // ══════════════════════════════════════════════════════════
  // PHASE 1: HOME ROW — LEFT HAND (Lessons 1–5)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-001",
    title: "Home Row Left: ক ত (j k)",
    subtitle: "j=ক এবং k=ত — ডান হাতের তর্জনী ও মধ্যমা আঙুল",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ক ত",
    text: "ক ত ক ত কক তত কত তক কক তত কক তত কত তক তক কত ককত তকক",
    order: 1,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-002",
    title: "Home Row Left: দ স (l ;)",
    subtitle: "l=দ এবং ;=স — ডান হাতের অনামিকা ও কনিষ্ঠা আঙুল",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "দ স",
    text: "দ স দ স দদ সস দস সদ দদ সস দদ সস দস সদ সদ দস দদস সদদ",
    order: 2,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-003",
    title: "Home Row Left: ি া (d f)",
    subtitle: "d=ি (ই-কার) এবং f=া (আ-কার) — বাম হাতের মধ্যমা ও তর্জনী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ি া",
    text: "ি া ি া িা াি িি াা িা াি িি াা িা াি াি িা িিা ািি",
    order: 3,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-004",
    title: "Home Row Left: ু ৃ (s a)",
    subtitle: "s=ু (উ-কার) এবং a=ৃ (ঋ-কার) — বাম হাতের অনামিকা ও কনিষ্ঠা",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ু ৃ",
    text: "ু ৃ ু ৃ ুু ৃৃ ুৃ ৃু ুু ৃৃ ুু ৃৃ ুৃ ৃু ৃু ুৃ ুুৃ ৃুু",
    order: 4,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-005",
    title: "Home Row: ্ (g) — Link / Hasanta Key",
    subtitle: "g=্ — যুক্তবর্ণ তৈরির গুরুত্বপূর্ণ কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "্",
    text: "ক্ ত্ দ্ স্ ক্ত ক্ত ন্দ স্ত ক্ ত্ দ্ স্ ক্ত ন্দ স্ত ক্ত",
    order: 5,
    targetWpm: 8,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 2: HOME ROW — RIGHT HAND (Lessons 6–7)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-006",
    title: "Home Row Right Combo: ব ক ত দ স",
    subtitle: "ডান হাতের হোম কীবোর্ড কী (h, j, k, l, ;) একসাথে",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "ব ক ত দ স",
    text: "ব ক ত দ স বক তদ সব বব কক তত দদ সস বক তদ দস কব বকতদস",
    order: 6,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-007",
    title: "Home Row Full Mix: Vowel Signs + Consonants",
    subtitle: "কার চিহ্ন ও ব্যঞ্জনবর্ণ মিলিয়ে প্রথম পর্যায়ের সমন্বয়",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "ৃ ু ি া ব ক ত দ স",
    text: "কা কি কু কৃ বা বক তত দদ সস কা কি কু কৃ বা বক তত দদ সস",
    order: 7,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 3: TOP ROW (Lessons 8–14)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-008",
    title: "Top Row: য ড প (w e r)",
    subtitle: "w=য, e=ড, r=প — বাম হাতের উপরের তিনটি কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "য ড প",
    text: "য ড প যড পয যয ডড পপ যড পয যড পয যয ডড পপ যড পয যডপ পডয",
    order: 8,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-009",
    title: "Top Row: ট ে (t ])",
    subtitle: "t=ট এবং ]=ে (এ-কার) — বাম তর্জনী ও ডান কনিষ্ঠা",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "ট ে",
    text: "ট ে ট ে টট েে টে েট টট েে টট েে টে েট েট টে ততে েটট",
    order: 9,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-010",
    title: "Top Row: চ জ হ (y u i)",
    subtitle: "y=চ, u=জ, i=হ — ডান হাতের উপরের তিনটি কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "চ জ হ",
    text: "চ জ হ চজ হচ চচ জজ হহ চজ হচ চজ হচ চচ জজ হহ চজ হচ চজহ হজচ",
    order: 10,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-011",
    title: "Top Row: গ ড় ে (o p ])",
    subtitle: "o=গ, p=ড়, ]=ে — ডান হাতের অনামিকা ও কনিষ্ঠা",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "গ ড় ে",
    text: "গ ড় ে গড় েগ গগ ড়ড় েে গড় েগ গড় েগ গগ ড়ড় েে গড় েগ গড়ে",
    order: 11,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-012",
    title: "Top Row Left Combo",
    subtitle: "বাম হাতের টপ রো কীগুলোর সমন্বিত ড্রিল",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "য ড প ট ে",
    text: "য ড প ট ে যড পে টয ডে পট যডপ টেয ডপট েযড যডপটে েটপডয",
    order: 12,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-013",
    title: "Top Row Right Combo",
    subtitle: "ডান হাতের টপ রো কীগুলোর সমন্বিত ড্রিল",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "চ জ হ গ ড়",
    text: "চ জ হ গ ড় চজ হগ ড়চ জহ চজ হগ চজহ গড় হগজ চজহগড় ড়গহজচ",
    order: 13,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-014",
    title: "Top Row Full Mix",
    subtitle: "উপরের সারির সব অক্ষরের মিশ্র কীবোর্ড টাইপিং",
    category: "bangla",
    level: "beginner",
    type: "combo",
    focusKeys: "য ড প ট চ জ হ গ ড় ে",
    text: "েয ডপ চজ হগ ড়ট েযডপ চজহগ েড চহ যপ জগ টড় েযডপচজহগড়",
    order: 14,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 4: BOTTOM ROW (Lessons 15–16)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-015",
    title: "Bottom Row Left: ্র ও (z x)",
    subtitle: "z=্র (র-ফলা) এবং x=ও — বাম হাতের নীচের কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "্র ও",
    text: "্র ও ্র ও ্র্র ওও ্রও ও্র ্র্র ওও ্র্র ওও ্রও ও্র ও্র ্রও ্র্রও",
    order: 15,
    targetWpm: 8,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-016",
    title: "Bottom Row Right: র ন ষ ম (v n m ,)",
    subtitle: "v=র, n=ন, m=ষ — ডান হাতের নীচের কী",
    category: "bangla",
    level: "beginner",
    type: "drill",
    focusKeys: "র ন ষ ম",
    text: "র ন ষ ম রন ষম নর মষ রর নন ষষ মম রন ষম মষ নর রনষম মষনর",
    order: 16,
    targetWpm: 8,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 5: ALL ROWS — SIMPLE WORDS (Lesson 17)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-017",
    title: "All Rows Combined Simple Words",
    subtitle: "শিফট কী ছাড়া সাধারণ বাংলা শব্দের ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "করন গরম চটি পকেট জেলি রতি গবম পতন চমক রগড় হিমজ তকরি",
    order: 17,
    targetWpm: 15,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 6: SHIFT KEYS — HOME ROW (Lessons 18–20)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-018",
    title: "Shift Home Left: ঋ ূ ী (A S D)",
    subtitle: "A=ঋ, S=ূ (ঊ-কার), D=ী (ঈ-কার) — শিফট+বাম হোম রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "ঋ ূ ী",
    text: "ঋ ূ ী ঋ ূ ী ঋূ ীঋ ঋঋ ূূ ীী ঋূ ীঋ ঋূী ীূঋ ঋূীঋ",
    order: 18,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-bijoy-019",
    title: "Shift Home Left: আ অ (F G)",
    subtitle: "F=আ, G=অ — স্বরবর্ণ আ এবং অ",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "আ অ",
    text: "আ অ আ অ আআ অঅ আঅ অআ আআ অঅ আআ অঅ আঅ অআ অআ আঅ আআঅ",
    order: 19,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-bijoy-020",
    title: "Shift Home Right: ভ খ থ ধ (H J K L)",
    subtitle: "H=ভ, J=খ, K=থ, L=ধ — শিফট+ডান হোম রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "ভ খ থ ধ",
    text: "ভ খ থ ধ ভখ থধ খভ ধথ ভভ খখ থথ ধধ ভখথধ ধথখভ ভখথধখ",
    order: 20,
    targetWpm: 10,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 7: SHIFT KEYS — TOP ROW (Lessons 21–22)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-021",
    title: "Shift Top Left: ্য ঢ ফ ঠ (W E R T)",
    subtitle: "W=্য, E=ঢ, R=ফ, T=ঠ — শিফট+বাম টপ রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্য ঢ ফ ঠ",
    text: "্য ঢ ফ ঠ ্যঢ ফঠ ঢ্য ঠফ ্য্য ঢঢ ফফ ঠঠ ্যঢফঠ ঠফঢ্য",
    order: 21,
    targetWpm: 10,
    targetAccuracy: 85,
  },
  {
    id: "bn-bijoy-022",
    title: "Shift Top Right: ছ ঝ ঞ ঘ ঢ় (Y U I O P)",
    subtitle: "Y=ছ, U=ঝ, I=ঞ, O=ঘ, P=ঢ় — শিফট+ডান টপ রো",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "ছ ঝ ঞ ঘ ঢ়",
    text: "ছ ঝ ঞ ঘ ঢ় ছঝ ঞঘ ঢ়ছ ঝঞ ছছ ঝঝ ঞঞ ঘঘ ঢ়ঢ় ছঝঞঘ ঘঞঝছ",
    order: 22,
    targetWpm: 10,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 8: SHIFT KEYS — BOTTOM ROW (Lesson 23)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-023",
    title: "Shift Bottom Row: ্য ৌ ৈ ল ণ শ",
    subtitle: "শিফটের সাথে নীচের সারির বর্ণ",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্য ৌ ৈ ল ণ শ",
    text: "্য ৌ ৈ ল ণ শ ্যৌ ৈল ণশ ্য্য ৌৌ ৈৈ লল ণণ শশ ্যৌৈলণশ",
    order: 23,
    targetWpm: 10,
    targetAccuracy: 85,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 9: NUMBERS (Lessons 24–26)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-024",
    title: "Numbers: ১ ২ ৩ ৪ ৫",
    subtitle: "সংখ্যা ১ থেকে ৫ (UniBijoy)",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "১ ২ ৩ ৪ ৫",
    text: "১২৩৪৫ ৫৪৩২১ ১১ ২২ ৩৩ ৪৪ ৫৫ ১২ ২৩ ৩৪ ৪৫ ৫১ ১২৩ ২৩৪ ৩৪৫",
    order: 24,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-025",
    title: "Numbers: ৬ ৭ ৮ ৯ ০",
    subtitle: "সংখ্যা ৬ থেকে ০ (UniBijoy)",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "৬ ৭ ৮ ৯ ০",
    text: "৬৭৮৯০ ০৯৮৭৬ ৬৬ ৭৭ ৮৮ ৯৯ ০০ ৬৭ ৭৮ ৮৯ ৯০ ০৬ ৬৭৮ ৭৮৯ ৮৯০",
    order: 25,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-026",
    title: "Numbers Full Combo: ১–০",
    subtitle: "সব বাংলা সংখ্যা একসাথে",
    category: "bangla",
    level: "intermediate",
    type: "combo",
    focusKeys: "১ ২ ৩ ৪ ৫ ৬ ৭ ৮ ৯ ০",
    text: "১২৩৪৫৬৭৮৯০ ০৯৮৭৬৫৪৩২১ ১২৩৪ ৫৬৭৮ ৯০১২ ৩৪৫৬ ৭৮৯০",
    order: 26,
    targetWpm: 14,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 10: CONJUNCTS (Lessons 27–28)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-027",
    title: "Simple Conjuncts: ক্ত ন্দ ন্ত ম্প",
    subtitle: "সহজ যুক্তবর্ণ (g = link key ্)",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্ ক ত ন দ ম প ল স",
    text: "ক্ত ন্দ ন্ত ম্প ল্প ম্ম ল্ম ল্ক স্ত ন্দ ন্ত ম্প ল্প ম্ম ল্ম",
    order: 27,
    targetWpm: 10,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-028",
    title: "Complex Conjuncts: ক্ষ জ্ঞ শ্চ",
    subtitle: "জটিল যুক্তবর্ণ — ক্ষ, জ্ঞ, শ্চ, চ্চ, ত্ত",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্ ক ষ জ ঞ শ চ ত",
    text: "ক্ষ জ্ঞ শ্চ চ্চ ত্ত ক্ষ জ্ঞ শ্চ চ্চ ত্ত ক্ষমা জ্ঞান নিশ্চয়",
    order: 28,
    targetWpm: 10,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 11: VARGA ASPIRATED PAIRS (Lessons 29–33)
  // Teaching: base key vs. Shift version side-by-side
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-029",
    title: "ক-বর্গ Pairs: ক↔খ গ↔ঘ",
    subtitle: "ক (j) ↔ খ (Shift+j) এবং গ (o) ↔ ঘ (Shift+o) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "ক খ গ ঘ",
    text: "ক খ ক খ কখ খক কক খখ গ ঘ গ ঘ গঘ ঘগ গগ ঘঘ কখগঘ ঘঘখক",
    order: 29,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-030",
    title: "চ-বর্গ Pairs: চ↔ছ জ↔ঝ",
    subtitle: "চ (y) ↔ ছ (Shift+y) এবং জ (u) ↔ ঝ (Shift+u) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "চ ছ জ ঝ",
    text: "চ ছ চ ছ চছ ছচ চচ ছছ জ ঝ জ ঝ জঝ ঝজ জজ ঝঝ চছজঝ ঝঝছচ",
    order: 30,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-031",
    title: "ট-বর্গ Pairs: ট↔ঠ ড↔ঢ",
    subtitle: "ট (t) ↔ ঠ (Shift+t) এবং ড (e) ↔ ঢ (Shift+e) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "ট ঠ ড ঢ",
    text: "ট ঠ ট ঠ টঠ ঠট টট ঠঠ ড ঢ ড ঢ ডঢ ঢড ডড ঢঢ টঠডঢ ঢঢঠট",
    order: 31,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-032",
    title: "ত-বর্গ Pairs: ত↔থ দ↔ধ",
    subtitle: "ত (k) ↔ থ (Shift+k) এবং দ (l) ↔ ধ (Shift+l) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "ত থ দ ধ",
    text: "ত থ ত থ তথ থত তত থথ দ ধ দ ধ দধ ধদ দদ ধধ তথদধ ধধথত",
    order: 32,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-033",
    title: "প-বর্গ Pairs: প↔ফ ব↔ভ",
    subtitle: "প (r) ↔ ফ (Shift+r) এবং ব (h) ↔ ভ (Shift+h) পেয়ার ড্রিল",
    category: "bangla",
    level: "intermediate",
    type: "pair",
    focusKeys: "প ফ ব ভ",
    text: "প ফ প ফ পফ ফপ পপ ফফ ব ভ ব ভ বভ ভব বব ভভ পফবভ ভভফপ",
    order: 33,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 12: PHOLA LESSONS (Lessons 34–37)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-034",
    title: "রেফ (র্): ধর্ম বর্গ কর্ম",
    subtitle: "রেফ = র + হসন্ত পরবর্তী বর্ণের উপরে লেখা হয়",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "র্",
    text: "র্ক র্ম র্ত র্প ধর্ম বর্গ কর্ম অর্থ পর্দা সর্ব ধর্ম বর্গ",
    order: 34,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-035",
    title: "র-ফলা (্র): প্রেম গ্রাম",
    subtitle: "র-ফলা = ব্যঞ্জনবর্ণ + হসন্ত + র → বর্ণের নিচে ছোট র",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্র",
    text: "ক্র গ্র প্র ত্র ব্র ম্র প্রেম গ্রাম দ্রুত ত্রাণ ব্রত ক্রম",
    order: 35,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-036",
    title: "য-ফলা (্য): বিদ্যা আত্যন্ত",
    subtitle: "য-ফলা = ব্যঞ্জনবর্ণ + হসন্ত + য → বর্ণের নিচে ছোট য",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্য",
    text: "ক্য গ্য ত্য ব্য ন্য বিদ্যা আত্যন্ত সত্য ন্যায় ভদ্য রাজ্য",
    order: 36,
    targetWpm: 12,
    targetAccuracy: 88,
  },
  {
    id: "bn-bijoy-037",
    title: "ব-ফলা (্ব): স্বপ্ন দ্বিতীয়",
    subtitle: "ব-ফলা = ব্যঞ্জনবর্ণ + হসন্ত + ব → বর্ণের নিচে ছোট ব",
    category: "bangla",
    level: "intermediate",
    type: "drill",
    focusKeys: "্ব",
    text: "ক্ব ত্ব দ্ব শ্ব স্ব স্বপ্ন স্বাধীন দ্বিতীয় দ্বার ব্যক্তি শ্বাস",
    order: 37,
    targetWpm: 12,
    targetAccuracy: 88,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 13: COMMON WORD FREQUENCY DRILLS (Lessons 38–39)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-038",
    title: "Top 25 Common Words Part 1",
    subtitle: "সর্বাধিক ব্যবহৃত ২৫টি বাংলা শব্দের প্রথম দল",
    category: "bangla",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "আমি তুমি সে আমরা তোমরা এই সেই এবং কিন্তু তার তাদের আমার তোমার",
    order: 38,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "bn-bijoy-039",
    title: "Top 25 Common Words Part 2",
    subtitle: "সর্বাধিক ব্যবহৃত ২৫টি বাংলা শব্দের দ্বিতীয় দল",
    category: "bangla",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "করা হওয়া বলা দেখা যাওয়া আসা থাকা দেওয়া নেওয়া জানা শোনা পাওয়া",
    order: 39,
    targetWpm: 15,
    targetAccuracy: 90,
  },

  // ══════════════════════════════════════════════════════════
  // PHASE 14: SENTENCES + PARAGRAPHS (Lessons 40–45)
  // ══════════════════════════════════════════════════════════
  {
    id: "bn-bijoy-040",
    title: "Sentences 1: Daily Life",
    subtitle: "দৈনন্দিন জীবনের সহজ বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    focusKeys: "all",
    text: "আমি বাংলায় গান গাই। বিজয় কীবোর্ড দিয়ে বাংলা লেখা অত্যন্ত সহজ এবং আরামদায়ক। নিয়মিত অনুশীলন করলে গতি অনেক বৃদ্ধি পাবে।",
    order: 40,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "bn-bijoy-041",
    title: "Sentences 2: Typing Practice",
    subtitle: "কীবোর্ড টাইপিং সম্পর্কিত বাক্য",
    category: "bangla",
    level: "intermediate",
    type: "sentence",
    focusKeys: "all",
    text: "কীবোর্ডের দিকে না তাকিয়ে টাইপ করলে গতি অনেক বৃদ্ধি পায়। সঠিক আঙুল সঠিক কী-তে স্থাপন করাই হলো টাচ টাইপিংয়ের মূল রহস্য।",
    order: 41,
    targetWpm: 16,
    targetAccuracy: 90,
  },
  {
    id: "bn-bijoy-042",
    title: "Paragraph 1: UniBijoy History",
    subtitle: "বিজয় কীবোর্ড সম্পর্কে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    focusKeys: "all",
    text: "বিজয় কীবোর্ড বাংলাদেশের একটি বহুল ব্যবহৃত এবং অত্যন্ত জনপ্রিয় কীবোর্ড লেআউট। এটি প্রথাগত প্রেস, প্রকাশনা শিল্প এবং সাধারণ দাপ্তরিক কাজে ইউনিকোড পদ্ধতিতে বাংলা লিখতে ব্যাপকভাবে ব্যবহৃত হয়। এর সুবিন্যস্ত কী বিন্যাস বাংলা লেখার গতি কয়েক গুণ বাড়িয়ে দেয়।",
    order: 42,
    targetWpm: 18,
    targetAccuracy: 92,
  },
  {
    id: "bn-bijoy-043",
    title: "Paragraph 2: Language & Technology",
    subtitle: "ভাষা ও প্রযুক্তি সম্পর্কে অনুচ্ছেদ",
    category: "bangla",
    level: "advanced",
    type: "paragraph",
    focusKeys: "all",
    text: "ডিজিটাল মাধ্যমে বাংলা লেখার জন্য সঠিক কীবোর্ড লেআউট জানা অত্যন্ত দরকারি। কীবোর্ড স্পর্শ করে অক্ষর চেনার অভ্যাস আমাদের টাইপিং দক্ষ করে তোলে। আধুনিক তথ্য প্রযুক্তির যুগে বাংলা লেখার পরিধি ক্রমেই বৃদ্ধি পাচ্ছে এবং এটি আমাদের কাজের গতি বাড়াতে সাহায্য করে।",
    order: 43,
    targetWpm: 20,
    targetAccuracy: 92,
  },
  {
    id: "bn-bijoy-044",
    title: "Speed Builder",
    subtitle: "উচ্চ গতিতে টাইপিং অনুশীলন",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "গতিশীলতা ও নির্ভুলতা অর্জনের জন্য কীবোর্ড টাইপিং অনুশীলনের কোনো বিকল্প নেই। প্রতিদিন অন্তত পনেরো থেকে ত্রিশ মিনিট নিয়ম মেনে টাইপ করার অভ্যাস রাখা জরুরি। সঠিক পোস্টার বজায় রাখলে দীর্ঘ সময় টাইপ করলেও হাতের ক্লান্তি আসে না।",
    order: 44,
    targetWpm: 22,
    targetAccuracy: 93,
  },
  {
    id: "bn-bijoy-045",
    title: "Final UniBijoy Mastery Challenge",
    subtitle: "বিজয় কীবোর্ডের চূড়ান্ত গতি পরীক্ষা",
    category: "bangla",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "মাতৃভাষা বাংলায় কীবোর্ড টাইপিং আয়ত্ত করা অত্যন্ত আনন্দের ও গৌরবের বিষয়। প্রযুক্তির কল্যাণে আমরা এখন সহজেই আমাদের মনের সব অনুভূতি বাংলায় নিখুঁতভাবে টাইপ করতে পারি। পেশাগত জীবনে কীবোর্ড টাইপিংয়ের দক্ষতা আমাদের অন্যদের থেকে এক ধাপ এগিয়ে রাখে।",
    order: 45,
    targetWpm: 25,
    targetAccuracy: 95,
  },
];
