/**
 * TypeMaster — English Lessons (50 lessons)
 * Home Row → Top Row → Bottom Row → Numbers → Symbols → Mastery
 */
import { Lesson } from "../types";

// ─────────────────────────────────────────────────────────────
// ENGLISH LESSONS — 50 lessons, beginner → mastery
// ─────────────────────────────────────────────────────────────
export const englishLessons: Lesson[] = [
  // ═══════════════════════════════════════════════
  // SECTION 1: HOME ROW (Left Hand)
  // ═══════════════════════════════════════════════
  {
    id: "en-001",
    title: "Home Row: F & D",
    subtitle: "Your index and middle finger anchor keys",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "f d",
    text: "f d f d f d ff dd fd df fd df fff ddd fff ddd fd fd fd df df df",
    order: 1,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "en-002",
    title: "Home Row: J & K",
    subtitle: "Your right-hand index and middle finger",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "j k",
    text: "j k j k j k jj kk jk kj jk kj jjj kkk jjj kkk jk jk jk kj kj kj",
    order: 2,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "en-003",
    title: "Home Row: F D + J K",
    subtitle: "Combine both hands on home row",
    category: "english",
    level: "beginner",
    type: "combo",
    focusKeys: "f d j k",
    text: "fj fj dk dk fj dk jf kd jd kf fd jk df kj fjdk dkfj fjdk dkfj",
    order: 3,
    targetWpm: 18,
    targetAccuracy: 90,
  },
  {
    id: "en-004",
    title: "Home Row: A & S",
    subtitle: "Left pinky and ring finger",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "a s",
    text: "a s a s a s aa ss as sa as sa aaa sss aaa sss as as sa sa as sa",
    order: 4,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "en-005",
    title: "Home Row: L & ;",
    subtitle: "Right ring and pinky finger",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "l ;",
    text: "l ; l ; l ; ll ;; l; ;l l; ;l lll ;;; lll ;;; l; l; ;l ;l l; ;l",
    order: 5,
    targetWpm: 15,
    targetAccuracy: 90,
  },
  {
    id: "en-006",
    title: "Home Row: A S D F",
    subtitle: "Complete left-hand home row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "a s d f",
    text: "asdf asdf fdsa fdsa aaaa ssss dddd ffff asdf fdsa asfd dsaf asdf fdsa",
    order: 6,
    targetWpm: 20,
    targetAccuracy: 90,
  },
  {
    id: "en-007",
    title: "Home Row: J K L ;",
    subtitle: "Complete right-hand home row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "j k l ;",
    text: "jkl; jkl; ;lkj ;lkj jjjj kkkk llll ;;;; jkl; ;lkj jl;k kl;j jkl; ;lkj",
    order: 7,
    targetWpm: 20,
    targetAccuracy: 90,
  },
  {
    id: "en-008",
    title: "Home Row: Full Row",
    subtitle: "All 8 home row keys together",
    category: "english",
    level: "beginner",
    type: "combo",
    focusKeys: "a s d f j k l ;",
    text: "asdf jkl; asdf jkl; aj sk dl f; asdfjkl; ;lkjfdsa fjdk dlas fjdk dlas",
    order: 8,
    targetWpm: 22,
    targetAccuracy: 90,
  },
  {
    id: "en-009",
    title: "Home Row: + G",
    subtitle: "Introduce the left index stretch",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "g",
    text: "gf fg gf fg gg gf fg ggg fff ggg fff gfg fgf gfgf fgfg gaaa gsss gddd gfff",
    order: 9,
    targetWpm: 20,
    targetAccuracy: 88,
  },
  {
    id: "en-010",
    title: "Home Row: + H",
    subtitle: "Introduce right index stretch",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "h",
    text: "hj jh hj jh hh jj hhh jjj hjh jhj hjhj jhjh hkkk hlll h;; hjkl; jkl;h",
    order: 10,
    targetWpm: 20,
    targetAccuracy: 88,
  },
  {
    id: "en-011",
    title: "Home Row: Words!",
    subtitle: "Real words using home row only",
    category: "english",
    level: "beginner",
    type: "word",
    focusKeys: "a s d f g h j k l ;",
    text: "had glad glad fall hall shall ask flask glad shall flask half ask glass dash",
    order: 11,
    targetWpm: 25,
    targetAccuracy: 92,
  },

  // ═══════════════════════════════════════════════
  // SECTION 2: TOP ROW
  // ═══════════════════════════════════════════════
  {
    id: "en-012",
    title: "Top Row: E & I",
    subtitle: "Most common English vowels",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "e i",
    text: "e i e i e i ee ii ei ie ei ie eee iii eee iii ei ei ie ie eiie ieei",
    order: 12,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-013",
    title: "Top Row: R & U",
    subtitle: "Index fingers on the top row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "r u",
    text: "r u r u r u rr uu ru ur ru ur rrr uuu rrr uuu ru ru ur ur ruur uurr",
    order: 13,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-014",
    title: "Top Row: W & O",
    subtitle: "Ring fingers on top row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "w o",
    text: "w o w o w o ww oo wo ow wo ow www ooo www ooo wo wo ow ow woo oww wowo owow",
    order: 14,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-015",
    title: "Top Row: Q & P",
    subtitle: "Pinky finger stretch on top row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "q p",
    text: "q p q p q p qq pp qp pq qp pq qqq ppp qqq ppp qp qp pq pq qpp pqq qpqp",
    order: 15,
    targetWpm: 15,
    targetAccuracy: 85,
  },
  {
    id: "en-016",
    title: "Top Row: T & Y",
    subtitle: "Index finger mid-stretch on top row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "t y",
    text: "t y t y t y tt yy ty yt ty yt ttt yyy ttt yyy ty ty yt yt tyyt yytty",
    order: 16,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-017",
    title: "Top Row: Left Side (Q W E R T)",
    subtitle: "Full left top row",
    category: "english",
    level: "beginner",
    type: "combo",
    focusKeys: "q w e r t",
    text: "qwert qwert qwert trewq trewq trewq qet rwt qwert trewq qrwet tewrq qwert",
    order: 17,
    targetWpm: 22,
    targetAccuracy: 88,
  },
  {
    id: "en-018",
    title: "Top Row: Right Side (Y U I O P)",
    subtitle: "Full right top row",
    category: "english",
    level: "beginner",
    type: "combo",
    focusKeys: "y u i o p",
    text: "yuiop yuiop yuiop poiuy poiuy poiuy yip uoi yop uip yuiop poiuy yuop piuy",
    order: 18,
    targetWpm: 22,
    targetAccuracy: 88,
  },
  {
    id: "en-019",
    title: "Top Row + Home Row: Mix",
    subtitle: "First big combo — all fingers working",
    category: "english",
    level: "beginner",
    type: "mixed-word",
    focusKeys: "top + home rows",
    text: "dire fire hire wire like pike hike side ride tide wide rode kite site wire",
    order: 19,
    targetWpm: 25,
    targetAccuracy: 90,
  },
  {
    id: "en-020",
    title: "Top Row: Words!",
    subtitle: "Common English words from top + home rows",
    category: "english",
    level: "beginner",
    type: "word",
    focusKeys: "top + home rows",
    text: "their there where right other first while these would quite older hotel after",
    order: 20,
    targetWpm: 28,
    targetAccuracy: 90,
  },

  // ═══════════════════════════════════════════════
  // SECTION 3: BOTTOM ROW
  // ═══════════════════════════════════════════════
  {
    id: "en-021",
    title: "Bottom Row: V & M",
    subtitle: "Index fingers on the bottom row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "v m",
    text: "v m v m v m vv mm vm mv vm mv vvv mmm vvv mmm vm vm mv mv vmvm mvmv",
    order: 21,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-022",
    title: "Bottom Row: C & ,",
    subtitle: "Middle fingers on the bottom row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "c ,",
    text: "c , c , c , cc ,, c, ,c c, ,c ccc ,,, ccc ,,, c, c, ,c ,c c,,c ,cc,",
    order: 22,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-023",
    title: "Bottom Row: X & .",
    subtitle: "Ring fingers on the bottom row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "x .",
    text: "x . x . x . xx .. x. .x x. .x xxx ... xxx ... x. x. .x .x x..x .xx.",
    order: 23,
    targetWpm: 15,
    targetAccuracy: 85,
  },
  {
    id: "en-024",
    title: "Bottom Row: Z & /",
    subtitle: "Pinky fingers on the bottom row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "z /",
    text: "z / z / z / zz // z/ /z z/ /z zzz /// zzz /// z/ z/ /z /z z//z /zz/",
    order: 24,
    targetWpm: 15,
    targetAccuracy: 85,
  },
  {
    id: "en-025",
    title: "Bottom Row: B & N",
    subtitle: "Inner index stretch on bottom row",
    category: "english",
    level: "beginner",
    type: "drill",
    focusKeys: "b n",
    text: "b n b n b n bb nn bn nb bn nb bbb nnn bbb nnn bn bn nb nb bnbn nbnb",
    order: 25,
    targetWpm: 18,
    targetAccuracy: 88,
  },
  {
    id: "en-026",
    title: "Bottom Row: Full (Z X C V B  N M , . /)",
    subtitle: "All bottom row keys",
    category: "english",
    level: "beginner",
    type: "combo",
    focusKeys: "z x c v b n m , . /",
    text: "zxcvb nm,./ zxcvb nm,./ bvcxz /.,mn bvcxz /.,mn zcvb nm., zxcvbnm,./",
    order: 26,
    targetWpm: 20,
    targetAccuracy: 85,
  },
  {
    id: "en-027",
    title: "Bottom Row: Words!",
    subtitle: "Words using bottom + home rows",
    category: "english",
    level: "intermediate",
    type: "word",
    focusKeys: "all rows",
    text: "bank calm become vibrant combine between exactly maximum minimum combine",
    order: 27,
    targetWpm: 28,
    targetAccuracy: 90,
  },

  // ═══════════════════════════════════════════════
  // SECTION 4: ALL ROWS COMBINED
  // ═══════════════════════════════════════════════
  {
    id: "en-028",
    title: "All Rows: Short Common Words",
    subtitle: "Top 50 most used English words",
    category: "english",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "the and for are but not you all any can her was one our out day get has him how man new now old see two way who boy did its let put say she too use",
    order: 28,
    targetWpm: 30,
    targetAccuracy: 92,
  },
  {
    id: "en-029",
    title: "All Rows: Double Letters",
    subtitle: "Words with consecutive same letters",
    category: "english",
    level: "intermediate",
    type: "word",
    focusKeys: "all",
    text: "look feel good keep deep need seen feet been meet heel reel pool book cool",
    order: 29,
    targetWpm: 30,
    targetAccuracy: 92,
  },
  {
    id: "en-030",
    title: "Shift: Capital Letters",
    subtitle: "Start sentences with capitals",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: "Shift",
    text: "The And For Are But Not You All Any Can Her Was One Our Out Day Get Has Him How Man New Now Old See Two Way Who",
    order: 30,
    targetWpm: 25,
    targetAccuracy: 88,
  },
  {
    id: "en-031",
    title: "Shift: Mixed Case Words",
    subtitle: "Proper nouns and sentences",
    category: "english",
    level: "intermediate",
    type: "word",
    focusKeys: "Shift",
    text: "Bangladesh Dhaka Sylhet Chittagong London Paris Tokyo New York California",
    order: 31,
    targetWpm: 28,
    targetAccuracy: 90,
  },
  {
    id: "en-032",
    title: "Numbers: 1 2 3 4 5",
    subtitle: "Left half of the number row",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: "1 2 3 4 5",
    text: "12345 54321 11 22 33 44 55 12 23 34 45 51 123 234 345 451 512 12345 54321",
    order: 32,
    targetWpm: 20,
    targetAccuracy: 88,
  },
  {
    id: "en-033",
    title: "Numbers: 6 7 8 9 0",
    subtitle: "Right half of the number row",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: "6 7 8 9 0",
    text: "67890 09876 66 77 88 99 00 67 78 89 90 06 678 789 890 906 067 67890 09876",
    order: 33,
    targetWpm: 20,
    targetAccuracy: 88,
  },
  {
    id: "en-034",
    title: "Numbers: All 0-9",
    subtitle: "Full number row fluency",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: "0-9",
    text: "1234567890 0987654321 1234 5678 9012 3456 7890 123456 789012 1234567890",
    order: 34,
    targetWpm: 22,
    targetAccuracy: 88,
  },
  {
    id: "en-035",
    title: "Symbols: ! @ # $ %",
    subtitle: "Left Shift number symbols",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: "! @ # $ %",
    text: "! @ # $ % !@ @# #$ $% %! !@ @# #$ $% 100% $50 #1 @user !alert",
    order: 35,
    targetWpm: 18,
    targetAccuracy: 85,
  },
  {
    id: "en-036",
    title: "Symbols: ^ & * ( )",
    subtitle: "Right Shift number symbols",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: "^ & * ( )",
    text: "^ & * ( ) ^& &* *( () )^ ^& &* *( () 5^2 a&b c*d (e) )f^ func(x) arr[0]",
    order: 36,
    targetWpm: 18,
    targetAccuracy: 85,
  },
  {
    id: "en-037",
    title: "Punctuation Mastery",
    subtitle: "Commas, periods, colons, semicolons",
    category: "english",
    level: "intermediate",
    type: "drill",
    focusKeys: ". , : ; ? !",
    text: "Hello, world. How are you? I am fine: thank you; very much! Yes, that is right.",
    order: 37,
    targetWpm: 25,
    targetAccuracy: 90,
  },

  // ═══════════════════════════════════════════════
  // SECTION 5: SENTENCES & PARAGRAPHS
  // ═══════════════════════════════════════════════
  {
    id: "en-038",
    title: "Sentences: Simple",
    subtitle: "Short declarative sentences",
    category: "english",
    level: "intermediate",
    type: "sentence",
    focusKeys: "all",
    text: "The lazy brown dog slept peacefully under the old oak tree. A quick red fox darted across the narrow gravel path. She wrote a beautiful poem in her notebook, and he read the entire book from cover to cover.",
    order: 38,
    targetWpm: 30,
    targetAccuracy: 92,
  },
  {
    id: "en-039",
    title: "Sentences: Questions",
    subtitle: "Question-mark sentence practice",
    category: "english",
    level: "intermediate",
    type: "sentence",
    focusKeys: "all",
    text: "Where are you going for your summer vacation? What is the departure time of the train? How was your weekend trip to the mountains? Can you please help me translate this document into English?",
    order: 39,
    targetWpm: 30,
    targetAccuracy: 92,
  },
  {
    id: "en-040",
    title: "Sentences: Compound",
    subtitle: "Multi-clause sentences",
    category: "english",
    level: "advanced",
    type: "sentence",
    focusKeys: "all",
    text: "The quick brown fox jumps over the lazy dog in a single elegant leap. Pack my box with five dozen liquor jugs of fine old crystal. A quiet mind produces great ideas, and a steady hand creates beautiful art.",
    order: 40,
    targetWpm: 35,
    targetAccuracy: 93,
  },
  {
    id: "en-041",
    title: "Speed Builder: 3-Letter Words",
    subtitle: "Short words for speed rhythm",
    category: "english",
    level: "advanced",
    type: "word",
    focusKeys: "all",
    text: "the and for are but not you all any can her was one our out day get has him how man new now old see two way who boy did its let put say she too use try yet",
    order: 41,
    targetWpm: 40,
    targetAccuracy: 93,
  },
  {
    id: "en-042",
    title: "Speed Builder: 5-Letter Words",
    subtitle: "Medium-length vocabulary for WPM boost",
    category: "english",
    level: "advanced",
    type: "word",
    focusKeys: "all",
    text: "their there which while first about would other these after every where those light night right might sight fight quite often table",
    order: 42,
    targetWpm: 38,
    targetAccuracy: 93,
  },
  {
    id: "en-043",
    title: "Programming: Common Keywords",
    subtitle: "Python / JavaScript terminology",
    category: "english",
    level: "advanced",
    type: "word",
    focusKeys: "all",
    text: "function return const let var import export default class extends interface type string number boolean array object null undefined",
    order: 43,
    targetWpm: 35,
    targetAccuracy: 92,
  },
  {
    id: "en-044",
    title: "Tech Text: Code-Style",
    subtitle: "Mixed symbols and code constructs",
    category: "english",
    level: "advanced",
    type: "sentence",
    focusKeys: "all + symbols",
    text: "const result = arr.filter(x => x > 0).map(x => x * 2); console.log(result);",
    order: 44,
    targetWpm: 28,
    targetAccuracy: 90,
  },
  {
    id: "en-045",
    title: "Paragraph: Technology",
    subtitle: "Real-world paragraph on software",
    category: "english",
    level: "advanced",
    type: "paragraph",
    focusKeys: "all",
    text: "Developing muscle memory for typing is a gradual cognitive process that requires consistent daily dedication. As your fingers repeatedly discover the exact coordinates of each physical key, the brain shifts the cognitive load from conscious thought to automatic motor routines. This transition ultimately frees up your conscious attention to focus entirely on creative thinking and composition.",
    order: 45,
    targetWpm: 35,
    targetAccuracy: 93,
  },
  {
    id: "en-046",
    title: "Paragraph: Bangladesh",
    subtitle: "Cultural paragraph about Bangladesh",
    category: "english",
    level: "advanced",
    type: "paragraph",
    focusKeys: "all",
    text: "Bangladesh is a stunningly green deltaic nation in South Asia, bordered closely by India and the hills of Myanmar. The majestic Padma, Meghna, and Jamuna rivers form a vast, intricate network of waterways that sustains millions of livelihoods. The nation is globally respected for its rich heritage, classical poetry, folk music, and the historic Language Movement of 1952.",
    order: 46,
    targetWpm: 38,
    targetAccuracy: 93,
  },
  {
    id: "en-047",
    title: "Mastery: Business Email",
    subtitle: "Professional prose under pressure",
    category: "english",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "Dear Mr. Ahmed, I hope this email finds you well. I am writing to follow up on our previous board discussion regarding the upcoming software development project. Could you please confirm the revised development timeline and send over the updated technical specifications by Friday afternoon? Thank you for your continued cooperation.",
    order: 47,
    targetWpm: 40,
    targetAccuracy: 95,
  },
  {
    id: "en-048",
    title: "Mastery: Speed Text 1",
    subtitle: "Push your WPM ceiling",
    category: "english",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "Speed and accuracy are the twin pillars of professional typing, but you must never sacrifice precision for raw speed. Once your fingers develop deep spatial awareness of the layout, your velocity will scale naturally without conscious effort. Focus on maintaining a relaxed, rhythmic typing flow rather than forcing key strikes.",
    order: 48,
    targetWpm: 45,
    targetAccuracy: 95,
  },
  {
    id: "en-049",
    title: "Mastery: Speed Text 2",
    subtitle: "Advanced long-form paragraph",
    category: "english",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "The modern freelance economy has opened up massive global opportunities for individuals with high-speed typing and transcription capabilities. Professionals who write quickly and accurately can complete complex reports faster, handle a larger volume of client work, and increase their earning potential. Developing this skill is a direct investment in your long-term career growth.",
    order: 49,
    targetWpm: 48,
    targetAccuracy: 95,
  },
  {
    id: "en-050",
    title: "Grand Finale: Expert Challenge",
    subtitle: "The ultimate English typing test",
    category: "english",
    level: "mastery",
    type: "paragraph",
    focusKeys: "all",
    text: "In the rapidly evolving digital landscape of modern technology, the capability to communicate swiftly and accurately through typing has become an indispensable professional asset. From software engineers writing clean, optimized code to investigative journalists reporting breaking news, every single keystroke carries professional weight. The true mastery of this valuable craft begins with anchor keys and builds to automatic fluency.",
    order: 50,
    targetWpm: 50,
    targetAccuracy: 96,
  },
];
